#!/bin/bash
# Build walk_forward_tasks.txt for Slurm array jobs (one line = one training task).
#
#   ./generate_walk_forward_tasks.sh
#
# Columns: crop  country  model  [fold]
#   - NL, DE, … : no fold column → one job runs all walk-forward folds
#   - US, BR (if SPLIT_FOLDS_COUNTRIES): fold 0..TEST_YEARS-1 → one job per fold
#
# Env:
#   SPLIT_FOLDS_COUNTRIES="US BR"   # empty = never split by fold
#   TEST_YEARS=5
#   WF_MODELS="patchtst xlinear"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/walk_forward_env.sh"

MIN_YEARS="${MIN_YEARS:-8}"
EXCLUDED_COUNTRIES="${EXCLUDED_COUNTRIES:-}"
MODELS="${WF_MODELS:-patchtst xlinear}"
SPLIT_FOLDS_COUNTRIES="${SPLIT_FOLDS_COUNTRIES:-US BR}"
TEST_YEARS="${TEST_YEARS:-5}"
OUT_FILE="${OUT_FILE:-$SCRIPT_DIR/walk_forward_tasks.txt}"
YEARS_JSON="${CONFIG_DIR}/years_dict.json"

{
    echo "# crop country model [fold]  (generated by generate_walk_forward_tasks.sh)"
    echo "# SPLIT_FOLDS_COUNTRIES=${SPLIT_FOLDS_COUNTRIES:-<none>}  TEST_YEARS=${TEST_YEARS}"
    run_python -c "
import json
with open('$YEARS_JSON') as f:
    data = json.load(f)
min_years = $MIN_YEARS
excluded = set('$EXCLUDED_COUNTRIES'.split())
models = '$MODELS'.split()
split_countries = set('$SPLIT_FOLDS_COUNTRIES'.split())
test_years = $TEST_YEARS
for crop in sorted(data.keys()):
    for country, years in sorted(data[crop].items()):
        if len(years) < min_years or country in excluded:
            continue
        for model in models:
            if country in split_countries:
                for fold in range(test_years):
                    print(crop, country, model, fold)
            else:
                print(crop, country, model)
"
} > "$OUT_FILE"

n=$(grep -v '^#' "$OUT_FILE" | grep -c . || true)
n_split=$(grep -v '^#' "$OUT_FILE" | awk 'NF>=4' | wc -l)
n_single=$(grep -v '^#' "$OUT_FILE" | awk 'NF==3' | wc -l)
echo "Wrote $OUT_FILE: $n tasks ($n_single all-folds, $n_split single-fold) — $(wc -l < "$OUT_FILE") lines with header"
echo "Slurm array (0-based): sbatch --array=0-$((n - 1)) walk_forward_array.slurm"
echo "Tip: use longer #SBATCH --time for US/BR fold jobs (e.g. 2-00:00:00)"
